import React, { useEffect, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
const session = () => { try { return JSON.parse(localStorage.getItem("xedruo_session") || "null"); } catch { return null; } };
const call = async (path, options = {}) => { const s = session(); const r = await fetch(`${API_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(s?.access_token ? { Authorization: `Bearer ${s.access_token}` } : {}), ...(options.headers || {}) } }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `Request failed (${r.status})`); return d; };

export default function DeveloperDomainManager({ project }) {
  const [domains, setDomains] = useState([]); const [providers, setProviders] = useState([]); const [domain, setDomain] = useState(""); const [dns, setDns] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const data = await call(`/api/company-domains?project_id=${encodeURIComponent(project.id)}`); setDomains(data.domains || []); setProviders(data.providers || []); };
  useEffect(() => { if (project?.id) load().catch(e => setMessage(e.message)); }, [project?.id]);
  const add = async () => { if (!domain.trim()) return; setBusy(true); setMessage(""); try { const data = await call("/api/company-domains", { method: "POST", body: JSON.stringify({ company_id: project.company_id, project_id: project.id, domain }) }); setDomain(""); setDns(data.dns); await load(); setMessage("Domain added. Buy it if you have not already, then add the DNS record shown below."); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const verify = async id => { setBusy(true); setMessage(""); try { await call(`/api/company-domains/${id}/verify`, { method: "POST" }); await load(); setMessage("Domain ownership verified. You can now activate it."); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const activate = async id => { setBusy(true); setMessage(""); try { await call(`/api/company-domains/${id}/activate`, { method: "POST" }); await load(); setMessage("Domain activated for this website."); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h3 className="text-lg font-semibold">Website domain</h3><p className="text-sm text-slate-500 mt-1">Buy a domain from a registrar, then connect it here. No backend work required.</p></div><span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-400">{domains.length} domain{domains.length === 1 ? "" : "s"}</span></div>
    <div className="grid md:grid-cols-[1fr_auto] gap-3 mt-5"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="yourcompany.com" className="rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 outline-none"/><button disabled={busy || !domain.trim()} onClick={add} className="rounded-xl bg-white text-slate-950 px-5 py-3 font-semibold disabled:opacity-50">Connect domain</button></div>
    <div className="mt-4"><p className="text-xs uppercase tracking-wider text-slate-500 mb-2">Buy a domain</p><div className="flex flex-wrap gap-2">{providers.map(p=><a key={p.slug} href={p.url} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800">{p.name} ↗</a>)}</div></div>
    {dns && <div className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><p className="font-medium text-amber-200">One DNS verification step</p><p className="text-sm text-slate-400 mt-1">At your domain provider, create this TXT record:</p><div className="mt-3 grid sm:grid-cols-2 gap-2 text-xs font-mono"><div className="rounded-lg bg-slate-950 p-3">Name: {dns.name}</div><div className="rounded-lg bg-slate-950 p-3 break-all">Value: {dns.value}</div></div><p className="text-xs text-slate-500 mt-3">After saving the DNS record, return here and click Verify.</p></div>}
    <div className="mt-5 space-y-2">{domains.map(d=><div key={d.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><p className="font-medium">{d.domain}</p><p className="text-xs text-slate-500 mt-1">{d.status === "active" ? "Live" : d.status === "verified" ? "Ownership verified" : "Waiting for verification"}</p></div><div className="flex gap-2">{d.status !== "active" && <button disabled={busy} onClick={()=>verify(d.id)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300">Verify</button>}{d.status === "verified" && <button disabled={busy} onClick={()=>activate(d.id)} className="rounded-lg bg-white text-slate-950 px-3 py-2 text-xs font-semibold">Activate website</button>}</div></div>)}</div>
    {message && <p className="text-sm text-slate-400 mt-4">{message}</p>}
  </div>;
}
