import { Router } from "express";
import Anthropic from "@anthropic-ai/sdk";
import { supabaseAdmin } from "../config/supabase";
import { AuthedRequest, requireAuth } from "../middleware/auth";

const router = Router();
const anthropic = process.env.ANTHROPIC_API_KEY ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY }) : null;
const COMPANY_AI_PROFILES: Record<string, string> = {
  pay: "Payments/financial-services customer AI: payment questions, transaction status, failed payments, refunds and escalation; never fabricate transaction facts.",
  play: "Entertainment/play customer AI: product, content, account and service questions, recommendations and escalation.",
  sportruo: "Sports customer AI plus sports intelligence: support users and route forecasts/statistics to specialist sports analysis; predictions are probabilistic.",
  hireuo: "Hireuo customer AI plus Hireuo specialist AI: job matching, candidate-employer matching, CV analysis/revamping, skill-gap analysis, job-description improvement and interview preparation. Never make protected-class hiring decisions or invent qualifications.",
  adom: "Adom customer support and company operations AI.", agruo: "Agruo agriculture, sales, operations and customer-support AI.", healthruo: "Healthruo health-service operations and customer-support AI; do not diagnose or invent medical facts.",
  xedruo_education: "Xedruo Education learner support, education operations and academic-assistance AI.", xedruo_capital: "Xedruo Capital finance, investment operations and customer-support AI; distinguish analysis from financial advice.", xedruo_energy: "Xedruo Energy operations, sales and customer-support AI.", xedruo_logistics: "Xedruo Logistics routing, delivery, operations and customer-support AI.", xedruo_properties: "Xedruo Properties property operations, listings, sales/leasing and customer-support AI.", spacetruo: "Spacetruo project/space operations and customer-support AI.", enit_ai: "Enit AI central orchestration and cross-company intelligence.", xedruo: "Xedruo parent-company executive, governance and cross-company intelligence."
};
const SYSTEM = `You are the private company-aware AI for Xedruo. Every operating company has its own customer-support AI and specialist business AI. Handle complaints empathetically, answer only from supplied facts and company context, classify cases, draft replies, recommend escalation and next actions. Never invent financial, transaction, customer, employee, job, operational, policy, legal or medical facts. Route requests to the appropriate Xedruo Function AI when specialist work is needed.`;
router.get("/memory", requireAuth, async (req: AuthedRequest, res) => { const company = String(req.query.company || "xedruo"); const { data, error } = await supabaseAdmin.from("company_ai_memory").select("id,company_slug,role,content,created_at").eq("user_id", req.user!.id).eq("company_slug", company).order("created_at", { ascending: true }).limit(100); if (error) return res.status(500).json({ error: error.message }); res.json({ messages: data || [], profile: COMPANY_AI_PROFILES[company] || "General company customer-support AI." }); });
router.post("/chat", requireAuth, async (req: AuthedRequest, res) => { if (!anthropic) return res.status(503).json({ error: "ANTHROPIC_API_KEY is not configured on the server" }); const { company, companyType, userMessage, mode = "company" } = req.body || {}; if (!company || !userMessage || typeof userMessage !== "string") return res.status(400).json({ error: "company and userMessage are required" }); try { const { data: history } = await supabaseAdmin.from("company_ai_memory").select("role,content").eq("user_id", req.user!.id).eq("company_slug", company).order("created_at", { ascending: false }).limit(20); const context = [...(history || [])].reverse().map((m: any) => ({ role: m.role === "assistant" ? "assistant" : "user", content: m.content })); await supabaseAdmin.from("company_ai_memory").insert({ user_id: req.user!.id, company_slug: company, role: "user", content: userMessage }); const profile = COMPANY_AI_PROFILES[company] || "General customer-support and operations AI for this company."; const message = await anthropic.messages.create({ model: "claude-sonnet-4-6", max_tokens: 1800, system: `${SYSTEM}\n\nActive company: ${company}\nCompany type: ${companyType || "Operating company"}\nAI profile: ${profile}\nMode: ${mode}`, messages: [...context, { role: "user", content: userMessage }] }); const answer = message.content.map((block: any) => block.type === "text" ? block.text : "").join("\n"); await supabaseAdmin.from("company_ai_memory").insert({ user_id: req.user!.id, company_slug: company, role: "assistant", content: answer }); res.json({ answer, company, mode }); } catch (err: any) { res.status(502).json({ error: err.message || "Company AI request failed" }); } });
router.delete("/memory", requireAuth, async (req: AuthedRequest, res) => { const company = String(req.query.company || "xedruo"); const { error } = await supabaseAdmin.from("company_ai_memory").delete().eq("user_id", req.user!.id).eq("company_slug", company); if (error) return res.status(500).json({ error: error.message }); res.json({ ok: true }); });
export default router;
