import React, { useState } from "react";
import { Bot, Code2, Database, FileText, Image, Mic2, Presentation, Send, Sparkles, Video } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

const MODES = [
  ["chat", "Chat", Bot, "Ask Enit anything."], ["build", "Build App", Code2, "Describe a real application to build."], ["analyze", "Data Analysis", Database, "Analyze data, trends and useful metrics."], ["presentation", "Presentation", Presentation, "Turn an idea or source into slides."], ["prompt", "Prompt Lab", Sparkles, "Turn natural language into an executable AI workflow."], ["document", "Documents", FileText, "Create or transform professional documents."], ["image", "Artwork", Image, "Create image and artwork generation briefs."], ["audio", "Audio", Mic2, "Create narration and audio workflows."], ["video", "Video", Video, "Create scripts, scenes and production workflows."]
];
const examples = {
  chat: "Explain how I can grow a new business in Nigeria.", build: "Build a real school management app with students, fees, attendance, results and a parent portal.", analyze: "Analyze this sales data and identify the biggest revenue opportunities.", presentation: "Create a 10-slide investor presentation for my company.", prompt: "Create a complete prompt for an AI to build a logistics management platform.", document: "Create a professional business proposal for a new energy company.", image: "Create a premium brand artwork concept for an African technology company.", audio: "Create a 60-second professional company introduction narration.", video: "Create a 90-second launch video for a new technology product."
};

export default function AIAssistant() {
  const [mode, setMode] = useState("chat"); const [prompt, setPrompt] = useState(""); const [context, setContext] = useState(""); const [output, setOutput] = useState(""); const [loading, setLoading] = useState(false); const [provider, setProvider] = useState("");
  async function run() {
    if (!prompt.trim() || loading) return; setLoading(true); setOutput("");
    try { const api = import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || "https://xedruo-backend.onrender.com"; const response = await fetch(`${api}/api/ai/enit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode, prompt, context }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Enit AI request failed"); setOutput(data.text || "No output returned."); setProvider(`${data.provider || "AI"} · ${data.model || "routed"}`); } catch (error) { setOutput(`Enit AI error: ${error.message}`); setProvider(""); } finally { setLoading(false); }
  }
  return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10 sticky top-0 z-20 bg-slate-950/95"><div className="max-w-7xl mx-auto px-4 md:px-6 py-4 flex items-center justify-between"><div><div className="flex items-center gap-2"><Sparkles className="text-cyan-300"/><span className="text-xl font-bold">Enit AI</span></div><p className="text-xs text-slate-500 mt-1">Public AI workspace · chat · app building · data · presentations · media</p></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-1 text-xs text-cyan-200">PUBLIC AI</span></div></header>
    <main className="max-w-7xl mx-auto px-4 md:px-6 py-6"><div className="grid lg:grid-cols-[250px_1fr] gap-5"><aside className="rounded-2xl border border-white/10 bg-white/5 p-3 h-fit"><div className="text-xs uppercase tracking-widest text-slate-500 px-2 pb-2">Workspace</div>{MODES.map(([id,label,Icon,desc]) => <button key={id} onClick={() => setMode(id)} className={`w-full rounded-xl p-3 text-left flex items-start gap-3 ${mode === id ? "bg-cyan-300/10 ring-1 ring-cyan-300/30" : "hover:bg-white/5"}`}><Icon size={18} className="mt-0.5 text-cyan-300"/><span><span className="block text-sm font-medium">{label}</span><span className="block text-[11px] text-slate-500 mt-0.5">{desc}</span></span></button>)}</aside>
      <section className="min-w-0"><div className="rounded-2xl border border-white/10 bg-white/5 p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs uppercase tracking-widest text-cyan-300">{MODES.find(m => m[0] === mode)?.[1]}</div><h1 className="text-2xl md:text-3xl font-bold mt-1">What do you want Enit to create?</h1></div><button onClick={() => setPrompt(examples[mode])} className="text-xs text-cyan-300 hover:text-cyan-200">Use example</button></div><div className="mt-5"><Textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder={examples[mode]} className="min-h-36 bg-black/20 border-white/10 text-white placeholder:text-slate-600" /></div><div className="mt-3"><Textarea value={context} onChange={e => setContext(e.target.value)} placeholder="Optional context: paste data, requirements, notes or source material..." className="min-h-24 bg-black/20 border-white/10 text-white placeholder:text-slate-600" /></div><div className="mt-4 flex justify-end"><Button onClick={run} disabled={loading || !prompt.trim()} size="lg" className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Send size={17}/>{loading ? "Working..." : "Run Enit"}</Button></div></div>
        <div className="mt-5 rounded-2xl border border-white/10 bg-white/5 overflow-hidden"><div className="px-5 py-4 border-b border-white/10 flex items-center justify-between"><span className="font-semibold">Output</span>{provider && <span className="text-xs text-slate-500">{provider}</span>}</div><div className="p-5 min-h-[420px] whitespace-pre-wrap text-sm leading-7 text-slate-300">{loading ? "Enit AI is working..." : output || "Your result will appear here."}</div></div>
        <div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{[[Code2,"Real apps","Plan working applications, architecture, pages, data models and implementation."],[Database,"Data intelligence","Analyze datasets and produce metrics, trends, decisions and chart recommendations."],[Presentation,"Presentations","Create slide narratives, speaker notes and visual directions."],[Bot,"Chat & prompts","Reason, write, plan and turn natural language into structured AI workflows."],[Image,"Visual creation","Create detailed briefs for artwork, branding and image generation."],[Mic2,"Audio & video","Create narration, scripts, scenes, captions and production workflows."]].map(([Icon,title,desc]) => <div key={title} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><Icon size={19} className="text-cyan-300"/><div className="font-medium mt-3">{title}</div><div className="text-xs text-slate-500 mt-1 leading-5">{desc}</div></div>)}</div></section></div></main></div>;
}
