import React, { useState } from "react";
import { Bot, Code2, Database, FileText, Image, Mic2, Presentation, Send, Sparkles, Video, CheckCircle2 } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

const MODES = [
  ["chat", "Chat", Bot, "Ask Enit anything."], ["build", "Build App", Code2, "Turn an idea into a real app plan."], ["analyze", "Analyze", Database, "Understand data and decisions."], ["presentation", "Slides", Presentation, "Create a professional presentation."], ["prompt", "Prompt Lab", Sparkles, "Create powerful AI workflows."], ["document", "Documents", FileText, "Create business documents."], ["image", "Artwork", Image, "Create visual briefs."], ["audio", "Audio", Mic2, "Create voice and audio plans."], ["video", "Video", Video, "Create scripts and scenes."]
];
const examples = { chat:"Explain how I can grow a new business in Nigeria.", build:"Build a school management app with students, fees, attendance, results and a parent portal.", analyze:"Analyze this sales data and identify the biggest opportunities.", presentation:"Create a 10-slide investor presentation for my company.", prompt:"Create a complete AI workflow for a logistics management platform.", document:"Create a professional business proposal for a new energy company.", image:"Create a premium brand artwork concept for Xedruo.", audio:"Create a 60-second professional company introduction.", video:"Create a 90-second launch video for a technology product." };

export default function AIAssistant(){
  const [mode,setMode]=useState("chat"),[prompt,setPrompt]=useState(""),[context,setContext]=useState(""),[output,setOutput]=useState(""),[loading,setLoading]=useState(false),[provider,setProvider]=useState("");
  async function run(){
    if(!prompt.trim()||loading)return; setLoading(true); setOutput(""); setProvider("");
    try{const api=import.meta.env.VITE_API_URL||import.meta.env.VITE_API_BASE_URL||"https://xedruo-backend.onrender.com"; const r=await fetch(`${api}/api/ai/enit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,prompt,context})}); const d=await r.json(); if(!r.ok)throw new Error(d.error||"Enit could not complete the request"); setOutput(d.text||"No result returned."); setProvider(`${d.provider||"Enit"}${d.model?` · ${d.model}`:""}`);}catch(e){setOutput(`Enit AI is temporarily unavailable. ${e.message}`);}finally{setLoading(false);}}
  return <div className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-white/10 bg-slate-950/95 sticky top-0 z-20"><div className="mx-auto max-w-7xl px-5 py-5 flex items-center justify-between"><div><div className="flex items-center gap-2"><Sparkles className="text-cyan-300"/><span className="text-xl font-black">Enit AI</span></div><p className="mt-1 text-xs text-slate-500">Public Xedruo AI workspace · no password required</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/5 px-3 py-1.5 text-xs text-emerald-300"><CheckCircle2 size={14}/> Public</div></div></header>
    <main className="mx-auto max-w-7xl px-5 py-7"><div className="grid lg:grid-cols-[220px_1fr] gap-6">
      <aside className="rounded-3xl border border-white/10 bg-white/[.035] p-3 h-fit"><div className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[.25em] text-slate-600">AI tools</div>{MODES.map(([id,label,Icon,desc])=><button key={id} onClick={()=>{setMode(id);setOutput("");}} className={`mb-1 w-full rounded-2xl p-3 text-left flex gap-3 ${mode===id?"bg-cyan-300/10 ring-1 ring-cyan-300/30":"hover:bg-white/5"}`}><Icon size={18} className="mt-0.5 shrink-0 text-cyan-300"/><span className="min-w-0"><span className="block text-sm font-semibold">{label}</span><span className="mt-0.5 block text-[10px] leading-4 text-slate-600">{desc}</span></span></button>)}</aside>
      <section className="min-w-0"><div className="rounded-3xl border border-white/10 bg-white/[.035] p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[.3em] text-cyan-300">{MODES.find(x=>x[0]===mode)?.[1]}</div><h1 className="mt-2 text-2xl font-black md:text-3xl">What can Enit do for you?</h1></div><button onClick={()=>setPrompt(examples[mode])} className="text-xs font-semibold text-cyan-300">Use example</button></div>
        <Textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={examples[mode]} className="mt-6 min-h-36 resize-y rounded-2xl border-white/10 bg-black/20 text-white placeholder:text-slate-600"/>
        <Textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Optional context, data, requirements or notes" className="mt-3 min-h-20 resize-y rounded-2xl border-white/10 bg-black/20 text-white placeholder:text-slate-600"/>
        <div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-600">Your request is processed by the Xedruo AI backend.</span><Button onClick={run} disabled={loading||!prompt.trim()} size="lg" className="rounded-2xl bg-cyan-300 px-6 font-bold text-slate-950 hover:bg-cyan-200"><Send size={16}/>{loading?"Working…":"Run Enit"}</Button></div></div>
        <div className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-slate-500">Result</div><div className="mt-1 text-sm font-semibold">{loading?"Enit is working…":"Your answer"}</div></div>{provider&&<span className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-slate-500">{provider}</span>}</div><div className="min-h-[360px] p-5 md:p-7 whitespace-pre-wrap text-sm leading-7 text-slate-300">{loading?"Thinking and preparing your result…":output||"Enter a request above and select Run Enit."}</div></div>
      </section></div></main>
  </div>;
}
