import React,{useEffect,useState} from "react";
import {UserPlus,Users,ShieldCheck,BarChart3,UserMinus,UserCheck,RefreshCw} from "lucide-react";
const api=(path,opts={})=>{const token=localStorage.getItem("xedruo_workforce_token");return fetch(`/api/workforce${path}`,{...opts,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;})};
export default function ChiefOfStaffWorkspace(){const [accounts,setAccounts]=useState([]),[companies,setCompanies]=useState([]),[name,setName]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[company,setCompany]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const [a,c]=await Promise.all([api("/accounts"),api("/companies")]);setAccounts(a.accounts||[]);setCompanies(c.companies||[]);if(!company&&c.companies?.[0])setCompany(c.companies[0].slug)}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function register(){setError("");setMessage("");if(!name||!username||!password||!company)return setError("Complete all developer fields.");setBusy(true);try{await api("/developers",{method:"POST",body:JSON.stringify({display_name:name,username,password,company_slug:company})});setMessage(`Developer ${name} registered for ${company}.`);setName("");setUsername("");setPassword("");await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function setStatus(id,enabled){try{await api(`/accounts/${id}/status`,{method:"POST",body:JSON.stringify({enabled})});await load()}catch(e){setError(e.message)}}
 const active=accounts.filter(a=>a.is_active).length,developers=accounts.filter(a=>a.role==="developer");
 return <div className="min-h-screen bg-slate-950 text-white p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap justify-between gap-5 mb-8"><div><div className="text-xs uppercase tracking-[.3em] text-cyan-300">Executive management</div><h1 className="text-3xl font-bold mt-2">Chief of Staff</h1><p className="mt-2 text-slate-400">Grant access, register developers, manage workflow and report on workforce activity.</p></div><button onClick={load} className="rounded-xl border border-white/10 px-4 py-3 flex items-center gap-2"><RefreshCw size={16}/> Refresh</button></div>
 <div className="grid gap-4 sm:grid-cols-3 mb-5"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><Users className="text-cyan-300"/><div className="text-2xl font-bold mt-3">{active}</div><div className="text-xs text-slate-500">active workforce accounts</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><UserPlus className="text-emerald-300"/><div className="text-2xl font-bold mt-3">{developers.length}</div><div className="text-xs text-slate-500">registered developers</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><BarChart3 className="text-violet-300"/><div className="text-2xl font-bold mt-3">{companies.length}</div><div className="text-xs text-slate-500">company units available</div></div></div>
 <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2 font-semibold"><UserPlus className="text-cyan-300" size={19}/> Register developer</div><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Developer full name" className="w-full rounded-xl bg-black/20 border border-white/10 p-3"/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Developer username" className="w-full rounded-xl bg-black/20 border border-white/10 p-3"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Developer password" type="password" className="w-full rounded-xl bg-black/20 border border-white/10 p-3"/><select value={company} onChange={e=>setCompany(e.target.value)} className="w-full rounded-xl bg-black/20 border border-white/10 p-3">{companies.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><button disabled={busy} onClick={register} className="w-full rounded-xl bg-cyan-300 text-slate-950 p-3 font-semibold disabled:opacity-40">{busy?"Registering…":"Register developer"}</button></div><div className="mt-5 rounded-xl bg-cyan-300/5 p-4 text-xs text-slate-400 flex gap-2"><ShieldCheck className="text-cyan-300 shrink-0" size={16}/> Developer access is company-scoped at the API. ELinit cannot cross that boundary.</div>{message&&<div className="mt-4 text-sm text-emerald-300">{message}</div>}{error&&<div className="mt-4 text-sm text-red-300">{error}</div>}</section>
 <section className="rounded-2xl border border-white/10 bg-white/5 overflow-hidden"><div className="p-5 border-b border-white/10"><h2 className="font-semibold">Management accounts</h2><p className="text-xs text-slate-500 mt-1">Grant, suspend and review workforce access.</p></div><div className="divide-y divide-white/5">{accounts.map(a=><div key={a.id} className="p-5 flex flex-wrap justify-between items-center gap-3"><div><div className="font-semibold">{a.display_name}</div><div className="text-xs text-slate-500">{a.username} · {a.role.replaceAll("_"," ")}{a.company_slug?` · ${a.company_slug}`:""}</div></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs ${a.is_active?"bg-emerald-300/10 text-emerald-300":"bg-red-300/10 text-red-300"}`}>{a.is_active?"active":"disabled"}</span>{a.role!=="governor"&&<button onClick={()=>setStatus(a.id,!a.is_active)} className="rounded-xl border border-white/10 px-3 py-2 text-xs flex items-center gap-1">{a.is_active?<><UserMinus size={14}/> Revoke</>:<><UserCheck size={14}/> Restore</>}</button>}</div></div>)}{!accounts.length&&<div className="p-10 text-center text-slate-500">No accounts found.</div>}</div></section></div></div></div>;
}
