import React, { useEffect, useState } from "react";
import { Code2, ExternalLink, GitBranch, Play, Send, ShieldCheck, Sparkles } from "lucide-react";
import { developerClient } from "../lib/developerClient";
import DeveloperDomainManager from "../components/DeveloperDomainManager";

export default function DeveloperControlCenter() {
  const [workspace,setWorkspace]=useState(null),[plugins,setPlugins]=useState([]),[prompt,setPrompt]=useState(""),[plan,setPlan]=useState(null),[result,setResult]=useState(null),[preview,setPreview]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let alive=true;Promise.all([developerClient.listProjects(),developerClient.listPlugins()]).then(async([p,pl])=>{const project=p.projects?.[0];if(!project)throw new Error("No company has been assigned to this developer account");const detail=await developerClient.getProject(project.id);const pv=await developerClient.getPreview(project.id);if(!alive)return;setWorkspace(detail);setPlugins(pl.plugins||[]);setPreview(pv);}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[]);
  async function ask(){if(!workspace?.project||!prompt.trim())return;setBusy(true);setError("");setResult(null);try{const d=await developerClient.promptProject(workspace.project.id,prompt.trim());setPlan(d.plan)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function execute(){if(!workspace?.project||!plan)return;setBusy(true);setError("");try{setResult(await developerClient.executePlan(workspace.project.id,prompt,plan))}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(loading)return <main className="min-h-screen bg-slate-950 text-white grid place-items-center">Opening your developer workstation…</main>;
  if(error&&!workspace)return <main className="min-h-screen bg-slate-950 text-white p-8"><div className="max-w-2xl mx-auto rounded-2xl border border-red-400/20 bg-red-400/5 p-6"><h1 className="text-xl font-semibold">Developer workstation unavailable</h1><p className="mt-2 text-red-200">{error}</p></div></main>;
  const project=workspace?.project,company=project?.companies||{};
  return <main className="min-h-screen bg-slate-950 text-white p-4 md:p-8"><div className="max-w-7xl mx-auto"><header className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><div className="flex items-center gap-2 text-cyan-300 text-xs uppercase tracking-[.25em]"><Code2 size={16}/>Developer Workstation</div><h1 className="text-3xl md:text-5xl font-semibold mt-2">{project?.name}</h1><p className="text-slate-400 mt-2">{company.industry||"Xedruo company project"} · {project?.slug}</p></div><button onClick={()=>preview?.previewUrl&&window.open(preview.previewUrl,"_blank","noopener,noreferrer")} className="rounded-xl bg-cyan-300 text-slate-950 px-4 py-2.5 font-semibold flex items-center gap-2"><Play size={16}/>Preview project</button></header>
  {error&&<div className="mb-5 rounded-xl border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-200">{error}</div>}
  <div className="grid xl:grid-cols-[1fr_320px] gap-5"><section className="space-y-5"><div className="rounded-2xl border border-white/10 bg-white/5 overflow-hidden"><div className="px-5 py-4 border-b border-white/10 flex items-center justify-between"><div><h2 className="font-semibold flex items-center gap-2"><Sparkles size={18} className="text-cyan-300"/>ELinit engineering assistant</h2><p className="text-xs text-slate-500 mt-1">Runs underneath this workstation. You do not select or log into ELinit.</p></div><span className="text-xs text-emerald-300 flex items-center gap-1"><ShieldCheck size={14}/>Company scoped</span></div><div className="p-5"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="Describe the code, UI, bug, feature, integration or deployment change you want…" className="w-full rounded-xl bg-black/30 border border-white/10 px-4 py-4 outline-none focus:border-cyan-300/40"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy||!prompt.trim()} onClick={ask} className="rounded-xl bg-white text-slate-950 px-5 py-3 font-semibold disabled:opacity-50 flex items-center gap-2"><Send size={16}/>{busy?"ELinit working…":"Ask ELinit to prepare the change"}</button>{plan&&<button disabled={busy} onClick={execute} className="rounded-xl bg-emerald-400/10 border border-emerald-400/30 text-emerald-300 px-5 py-3 font-semibold disabled:opacity-50 flex items-center gap-2"><GitBranch size={16}/>{busy?"Executing…":"Execute approved plan"}</button>}</div></div></div>
  {plan&&<div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/5 p-5"><h2 className="font-semibold">ELinit build plan</h2><p className="text-slate-300 mt-2 whitespace-pre-wrap">{plan.summary}</p>{Array.isArray(plan.implementation_steps)&&<ol className="mt-4 list-decimal list-inside space-y-2 text-sm text-slate-400">{plan.implementation_steps.map((x,i)=><li key={i}>{typeof x==="string"?x:JSON.stringify(x)}</li>)}</ol>}{Array.isArray(plan.files)&&<p className="text-xs text-slate-500 mt-4">Files: {plan.files.map(f=>f.path).join(", ")||"none"}</p>}</div>}
  {result&&<div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-5"><h2 className="font-semibold text-emerald-300">Execution result</h2><pre className="mt-3 overflow-auto text-xs text-slate-400">{JSON.stringify(result,null,2)}</pre></div>}<DeveloperDomainManager project={project}/></section>
  <aside className="space-y-5"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Your workstation</h2><p className="text-xs text-slate-500 mt-2">This session is automatically locked to the company assigned to your developer account.</p><div className="mt-4 rounded-xl bg-black/20 border border-white/10 p-4"><div className="text-xs text-slate-500">Assigned company</div><div className="font-semibold mt-1">{company.name||project?.name}</div><div className="text-xs text-slate-500 mt-1">{project?.slug}</div></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Preview</h2><p className="text-xs text-slate-500 mt-2 break-all">{preview?.previewUrl||"No preview URL configured"}</p><button disabled={!preview?.previewUrl} onClick={()=>window.open(preview.previewUrl,"_blank","noopener,noreferrer")} className="mt-3 w-full rounded-xl bg-white/10 py-3 text-sm flex items-center justify-center gap-2 disabled:opacity-40"><ExternalLink size={16}/>Open preview</button></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Engineering tools</h2><div className="mt-3 space-y-2">{plugins.map(p=><div key={p.id} className="flex items-center justify-between rounded-lg bg-black/20 px-3 py-2 text-sm"><span>{p.name}</span><span className={`text-xs ${p.connection?.connected?"text-emerald-300":"text-slate-600"}`}>{p.connection?.connected?"Connected":"Offline"}</span></div>)}</div></div></aside></div></div></main>;
}
