import React, { useEffect, useMemo, useState } from "react";
import { developerClient } from "../lib/developerClient";
import DeveloperDomainManager from "../components/DeveloperDomainManager";

export default function DeveloperControlCenter() {
  const [projects, setProjects] = useState([]); const [selected, setSelected] = useState(null); const [plugins, setPlugins] = useState([]);
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [prompting, setPrompting] = useState(false); const [error, setError] = useState("");
  const [description, setDescription] = useState(""); const [industry, setIndustry] = useState(""); const [features, setFeatures] = useState(""); const [prompt, setPrompt] = useState(""); const [plan, setPlan] = useState(null); const [result, setResult] = useState(null);
  const company = selected?.companies || {}; const domainPreview = useMemo(() => `${selected?.slug || "project"}.com`, [selected]);
  useEffect(() => { let alive = true; Promise.all([developerClient.listProjects(), developerClient.listPlugins()]).then(([p, pl]) => { if (!alive) return; setProjects(p.projects || []); setSelected(p.projects?.[0] || null); setPlugins(pl.plugins || []); }).catch(err => alive && setError(err.message)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  useEffect(() => { if (!selected) return; setDescription(selected.description || ""); setIndustry(company.industry || ""); setFeatures(""); setResult(null); setPlan(null); }, [selected?.id]);
  const selectProject = async project => { setError(""); setSelected(project); try { const data = await developerClient.getProject(project.id); setSelected(data.project); } catch (err) { setError(err.message); } };
  const runPrompt = async () => { if (!selected || !prompt.trim()) return; setPrompting(true); setError(""); try { const data = await developerClient.promptProject(selected.id, prompt.trim()); setPlan(data.plan); setPlugins((data.availablePlugins || []).map(p => ({ ...p, connection: data.connections?.[p.slug] || p.connection }))); } catch (err) { setError(err.message); } finally { setPrompting(false); } };
  const execute = async () => { if (!selected || !plan) return; setWorking(true); setError(""); try { setResult(await developerClient.executePlan(selected.id, prompt, plan)); } catch (err) { setError(err.message); } finally { setWorking(false); } };
  const advance = async () => { if (!selected) return; setWorking(true); setError(""); try { const data = await developerClient.advanceProject(selected.id, { industry, description, domain: domainPreview, prompt, features: features.split(/\n|,/).map(x => x.trim()).filter(Boolean) }); setSelected(data.project); setResult(data); } catch (err) { setError(err.message); } finally { setWorking(false); } };
  if (loading) return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><div className="text-slate-400">Loading developer projects…</div></main>;
  return <main className="min-h-screen bg-slate-950 text-white p-4 md:p-8"><div className="max-w-7xl mx-auto">
    <header className="mb-7"><p className="text-xs uppercase tracking-[0.28em] text-slate-500">Xedruo Power Holdings</p><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mt-2"><div><h1 className="text-3xl md:text-5xl font-semibold">Developer Workspace</h1><p className="text-slate-400 mt-2 max-w-3xl">Select a company, describe what you want, review the plan, then execute it through the connected development tools.</p></div><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-300">Developer access</span></div></header>
    {error && <div className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
    <div className="grid lg:grid-cols-[280px_1fr] gap-5">
      <aside className="rounded-2xl border border-slate-800 bg-slate-900 p-3 h-fit"><div className="px-3 py-2 mb-2"><p className="text-xs uppercase tracking-wider text-slate-500">Company projects</p><p className="text-sm text-slate-300 mt-1">Choose where to build</p></div><div className="space-y-1 max-h-[65vh] overflow-auto">{projects.map(project => <button key={project.id} onClick={() => selectProject(project)} className={`w-full rounded-xl px-3 py-3 text-left ${selected?.id === project.id ? "bg-white text-slate-950" : "text-slate-300 hover:bg-slate-800"}`}><div className="font-medium">{project.name}</div><div className="text-xs mt-1 text-slate-500">{project.companies?.industry || "Company platform"}</div></button>)}</div></aside>
      <section className="space-y-5">{selected ? <>
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5 md:p-7"><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><p className="text-sm text-slate-500">Building</p><h2 className="text-2xl md:text-3xl font-semibold">{selected.name}</h2><p className="text-slate-400 mt-1">{selected.slug}.com · {company.industry || "Company"}</p></div><span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-300">{selected.status}</span></div>
          <label className="block mt-6"><span className="text-sm text-slate-400">Build with prompt</span><textarea value={prompt} onChange={e => setPrompt(e.target.value)} rows={6} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-4 outline-none focus:border-slate-400" placeholder="Build a modern company website, customer portal, staff dashboard, payments, analytics and AI support. Use the existing database and deploy a preview." /></label>
          <div className="mt-3 flex flex-wrap gap-3"><button disabled={prompting || !prompt.trim()} onClick={runPrompt} className="rounded-xl bg-white text-slate-950 px-5 py-3 font-semibold disabled:opacity-50">{prompting ? "Planning build…" : "Generate build plan"}</button>{plan && <button disabled={working} onClick={execute} className="rounded-xl border border-emerald-500/40 bg-emerald-500/10 text-emerald-300 px-5 py-3 font-semibold disabled:opacity-50">{working ? "Executing…" : "Execute connected tools"}</button>}</div><p className="text-xs text-slate-500 mt-3">Xedruo handles the technical work behind the app. Every tool call is logged.</p>
        </div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">Developer plugins</h3><p className="text-sm text-slate-500 mt-1">Connected tools are available to the build agent.</p></div><span className="text-xs text-slate-500">{plugins.length} registered</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{plugins.map(plugin => <div key={plugin.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-center justify-between"><span className="font-medium">{plugin.name}</span><span className={`h-2 w-2 rounded-full ${plugin.connection?.connected ? "bg-emerald-400" : "bg-slate-600"}`} /></div><p className="text-xs text-slate-500 mt-2">{plugin.description}</p><div className="text-[11px] text-slate-600 mt-3">{plugin.connection?.connected ? "Connected" : "Not connected"} · {(plugin.capabilities || []).slice(0,4).join(" · ")}</div></div>)}</div></div>
        <DeveloperDomainManager project={selected} />
        {plan && <div className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-5"><h3 className="text-lg font-semibold">AI build plan</h3>{plan.summary && <p className="text-slate-300 mt-2 whitespace-pre-wrap">{plan.summary}</p>}{Array.isArray(plan.implementation_steps) && <ol className="mt-4 space-y-2 list-decimal list-inside text-sm text-slate-300">{plan.implementation_steps.map((step,i)=><li key={i}>{typeof step === "string" ? step : JSON.stringify(step)}</li>)}</ol>}{Array.isArray(plan.files) && plan.files.length > 0 && <p className="text-xs text-slate-500 mt-4">Files proposed: {plan.files.map(f=>f.path).join(", ")}</p>}{Array.isArray(plan.tool_actions) && <p className="text-xs text-slate-500 mt-2">Tool actions: {plan.tool_actions.map(x=>`${x.plugin}/${x.action}`).join(", ") || "none"}</p>}</div>}
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="grid md:grid-cols-2 gap-4"><label><span className="text-sm text-slate-400">Industry</span><input value={industry} onChange={e=>setIndustry(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" /></label><label><span className="text-sm text-slate-400">Default Xedruo domain</span><input value={domainPreview} readOnly className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-800 px-4 py-3 text-slate-400" /></label></div><label className="block mt-4"><span className="text-sm text-slate-400">Build specification</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" /></label><label className="block mt-4"><span className="text-sm text-slate-400">Additional work items</span><textarea value={features} onChange={e=>setFeatures(e.target.value)} rows={3} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3" /></label><div className="mt-5"><button disabled={working} onClick={advance} className="rounded-xl bg-white text-slate-950 px-5 py-3 font-semibold disabled:opacity-50">{working ? "Starting build…" : "Start tracked build"}</button></div></div>
        {result && <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5"><p className="text-sm text-emerald-300">Build execution finished.</p><pre className="mt-3 overflow-auto text-xs text-slate-400">{JSON.stringify(result, null, 2)}</pre></div>}
      </> : <div className="rounded-2xl border border-slate-800 bg-slate-900 p-8 text-slate-400">No developer projects are available.</div>}</section>
    </div></div></main>;
}
