import React,{useEffect,useState} from "react";
import {ArrowUpRight,BarChart3,Building2,CircleDollarSign,Gauge,Lightbulb,ShieldCheck,Target,TrendingUp,UserPlus,UserMinus} from "lucide-react";
const api=(path,opts={})=>{const token=localStorage.getItem("xedruo_workforce_token");return fetch(`/api/workforce${path}`,{...opts,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;})};
const data={weekly:{sales:1280000,income:1040000,expenses:620000,operations:91,transactions:982,failed:14},monthly:{sales:4860000,income:3970000,expenses:2310000,operations:94,transactions:3840,failed:41},yearly:{sales:51200000,income:41800000,expenses:24700000,operations:89,transactions:40120,failed:612}};
const money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n);
export default function GovernorDashboard({mode="operations"}){
 const [account,setAccount]=useState(null),[companies,setCompanies]=useState([]),[company,setCompany]=useState(localStorage.getItem("xedruo_selected_company")||"xedruo-power-holdings"),[accounts,setAccounts]=useState([]),[period,setPeriod]=useState("monthly"),[error,setError]=useState(""),[staffName,setStaffName]=useState(""),[staffUser,setStaffUser]=useState(""),[staffPass,setStaffPass]=useState("");const d=data[period];
 useEffect(()=>{(async()=>{try{const [m,c,a]=await Promise.all([api("/me"),api("/companies"),api("/accounts")]);if(m.account.role!=="governor")throw new Error("Governor access required");setAccount(m.account);setCompanies(c.companies||[]);setAccounts(a.accounts||[])}catch(e){setError(e.message)}})()},[]);
 function changeCompany(v){setCompany(v);localStorage.setItem("xedruo_selected_company",v)}
 async function remove(id){try{await api(`/accounts/${id}`,{method:"DELETE"});setAccounts(a=>a.map(x=>x.id===id?{...x,is_active:false}:x))}catch(e){setError(e.message)}}
 async function hireChief(){if(!staffName||!staffUser||!staffPass)return setError("Enter Chief of Staff name, username and password.");try{const r=await api("/accounts",{method:"POST",body:JSON.stringify({display_name:staffName,username:staffUser,password:staffPass,role:"chief_of_staff"})});setAccounts(a=>[r.account,...a]);setStaffName("");setStaffUser("");setStaffPass("")}catch(e){setError(e.message)}}
 if(error&&!account)return <div className="min-h-screen bg-slate-950 text-white grid place-items-center p-6"><div className="rounded-2xl border border-red-300/20 p-6"><h1 className="text-xl font-bold">Governor access unavailable</h1><p className="mt-2 text-red-200">{error}</p></div></div>;
 const net=d.income-d.expenses,success=Math.round(((d.transactions-d.failed)/d.transactions)*100),chiefs=accounts.filter(a=>a.role==="chief_of_staff");
 return <div className="min-h-screen bg-slate-950 text-white p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap justify-between gap-5 mb-7"><div><div className="text-xs uppercase tracking-[.3em] text-cyan-300">Governor · {account?.display_name||"Loading"}</div><h1 className="mt-2 text-3xl font-bold">{mode==="finance"?"Governor Finance & Growth":"Governor Operations & Performance"}</h1><p className="mt-2 text-slate-400">Executive access across Xedruo units · performance tracking and people authority</p></div><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4 flex items-center gap-3"><ShieldCheck className="text-cyan-300"/><div><div className="font-semibold">Governor authority</div><div className="text-xs text-slate-500">Hire, remove and enter any unit</div></div></div></div>
 <div className="grid gap-4 lg:grid-cols-[1fr_300px] mb-5"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><label className="text-xs uppercase tracking-widest text-slate-500">Active Xedruo unit</label><select value={company} onChange={e=>changeCompany(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-900 border border-white/10 p-4">{companies.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="text-xs text-slate-500">Current Governor</div><div className="font-semibold mt-1">{account?.display_name||"—"}</div><div className="text-xs text-slate-500 mt-1">{account?.username}</div></div></div>
 <div className="flex gap-2 mb-5">{["weekly","monthly","yearly"].map(x=><button key={x} onClick={()=>setPeriod(x)} className={`rounded-full px-4 py-2 text-sm capitalize ${period===x?"bg-cyan-300 text-slate-950 font-semibold":"bg-white/5 text-slate-300"}`}>{x}</button>)}</div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[["Sales",money(d.sales),TrendingUp],["Income",money(d.income),CircleDollarSign],["Expenses",money(d.expenses),Gauge],["Net",money(net),ArrowUpRight],["Operations",`${d.operations}%`,Building2],["Success",`${success}%`,Target]].map(([l,v,I])=><div key={l} className="rounded-2xl border border-white/10 bg-white/5 p-4"><I size={18} className="text-cyan-300"/><div className="mt-3 text-xl font-bold">{v}</div><div className="text-xs text-slate-500">{l}</div></div>)}</div>
 <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><BarChart3 className="text-cyan-300"/><h2 className="font-semibold">{company} performance</h2></div><p className="mt-5 leading-7 text-slate-300">Operations are running at {d.operations}% efficiency with {success}% transaction success. Governance priority: reduce avoidable failures, automate repetitive workflows and keep sales growth aligned with sustainable operating costs.</p><div className="mt-6 grid sm:grid-cols-3 gap-3"><div className="rounded-xl bg-black/20 p-4"><div className="text-xs text-slate-500">Financial health</div><div className="text-2xl font-bold mt-2">{Math.round(net/d.income*100)}%</div></div><div className="rounded-xl bg-black/20 p-4"><div className="text-xs text-slate-500">Transactions</div><div className="text-2xl font-bold mt-2">{d.transactions.toLocaleString()}</div></div><div className="rounded-xl bg-black/20 p-4"><div className="text-xs text-slate-500">Failed</div><div className="text-2xl font-bold mt-2">{d.failed}</div></div></div></section><section className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><Lightbulb className="text-amber-300"/><h2 className="font-semibold">Governance actions</h2></div><div className="mt-5 space-y-3"><div className="rounded-xl bg-black/20 p-4 text-sm text-slate-300">Review workflow reports and staff activity.</div><div className="rounded-xl bg-black/20 p-4 text-sm text-slate-300">Enter any company unit from the selector above.</div><div className="rounded-xl bg-black/20 p-4 text-sm text-slate-300">Hire or remove workforce accounts with an audit trail.</div></div></section></div>
 <section className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="font-semibold flex items-center gap-2"><UserPlus className="text-cyan-300"/> Chief of Staff authority</h2><div className="grid gap-3 md:grid-cols-4 mt-4"><input value={staffName} onChange={e=>setStaffName(e.target.value)} placeholder="Full name" className="rounded-xl bg-black/20 border border-white/10 p-3"/><input value={staffUser} onChange={e=>setStaffUser(e.target.value)} placeholder="Username" className="rounded-xl bg-black/20 border border-white/10 p-3"/><input value={staffPass} onChange={e=>setStaffPass(e.target.value)} placeholder="Password" type="password" className="rounded-xl bg-black/20 border border-white/10 p-3"/><button onClick={hireChief} className="rounded-xl bg-cyan-300 text-slate-950 p-3 font-semibold">Hire Chief of Staff</button></div><div className="mt-5 divide-y divide-white/5">{chiefs.map(c=><div key={c.id} className="py-4 flex justify-between items-center"><div><div className="font-semibold">{c.display_name}</div><div className="text-xs text-slate-500">{c.username} · {c.is_active?"active":"removed"}</div></div>{c.is_active&&<button onClick={()=>remove(c.id)} className="rounded-xl border border-red-300/20 text-red-300 px-3 py-2 text-xs flex gap-1 items-center"><UserMinus size={14}/> Remove</button>}</div>)}</div></section>
 {error&&<div className="mt-4 text-sm text-red-300">{error}</div>}</div></div>;
}
