import React, { useMemo, useState } from "react";
import { ArrowUpRight, BrainCircuit, Building2, CircleDollarSign, Gauge, Lightbulb, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";

const data={
 weekly:{sales:1280000,income:1040000,expenses:620000,operations:91,transactions:982,failed:14},
 monthly:{sales:4860000,income:3970000,expenses:2310000,operations:94,transactions:3840,failed:41},
 yearly:{sales:51200000,income:41800000,expenses:24700000,operations:89,transactions:40120,failed:612},
};
const money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n);

export default function GovernorDashboard({mode="operations"}){
 const company=new URLSearchParams(window.location.search).get("company")||"selected company"; const [period,setPeriod]=useState("monthly"); const d=data[period];
 const net=d.income-d.expenses; const successRate=Math.round(((d.transactions-d.failed)/d.transactions)*100);
 const suggestions=useMemo(()=>[
  d.expenses/d.income>.58?"Review the three largest expense categories and set a monthly cost-control target.":"Protect the current expense ratio and reinvest part of the surplus into high-performing operations.",
  d.failed>period==="yearly"?500:period==="monthly"?35:12?"Create a payment-failure review queue and retry failed transactions automatically.":"Transaction reliability is healthy; focus on conversion and customer retention.",
  d.operations<92?"Audit operational bottlenecks weekly and assign owners to the slowest processes.":"Operations are stable; use the next quarter to automate repetitive workflows.",
 ],[d,period]);
 const title=mode==="finance"?"Governor Finance & Growth Dashboard":"Governor Operations & Performance Dashboard";
 return <div className="min-h-screen bg-slate-950 text-white p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap justify-between gap-5 mb-8"><div><div className="text-xs uppercase tracking-[.3em] text-cyan-300">Executive governance</div><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-400">{company} · aggregate performance across operations, finance, sales and expenses</p></div><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4 flex gap-3 items-center"><ShieldCheck className="text-cyan-300"/><div><div className="text-sm font-semibold">Governor view</div><div className="text-xs text-slate-500">Executive decision support</div></div></div></div>
 <div className="flex gap-2 mb-5">{["weekly","monthly","yearly"].map(x=><button key={x} onClick={()=>setPeriod(x)} className={`rounded-full px-4 py-2 text-sm capitalize ${period===x?"bg-cyan-300 text-slate-950 font-semibold":"bg-white/5 text-slate-300"}`}>{x}</button>)}</div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[["Sales",money(d.sales),TrendingUp,"text-blue-300"],["Income",money(d.income),CircleDollarSign,"text-emerald-300"],["Expenses",money(d.expenses),Gauge,"text-rose-300"],["Net",money(net),ArrowUpRight,"text-cyan-300"],["Operations",`${d.operations}%`,Building2,"text-violet-300"],["Success",`${successRate}%`,Target,"text-green-300"]].map(([l,v,I,c])=><div key={l} className="rounded-2xl border border-white/10 bg-white/5 p-4"><I size={18} className={c}/><div className="mt-3 text-xl font-bold">{v}</div><div className="text-xs text-slate-500">{l}</div></div>)}</div>
 <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><Sparkles className="text-cyan-300" size={19}/><div><h2 className="font-semibold">AI dashboard analysis</h2><p className="text-xs text-slate-500">Automated executive interpretation for {period} performance</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-emerald-300/10 p-4"><div className="text-xs text-slate-400">Financial health</div><div className="mt-2 text-2xl font-bold text-emerald-300">{Math.round((net/d.income)*100)}%</div><div className="mt-1 text-xs text-slate-500">income retained after expenses</div></div><div className="rounded-xl bg-blue-300/10 p-4"><div className="text-xs text-slate-400">Transaction health</div><div className="mt-2 text-2xl font-bold text-blue-300">{successRate}%</div><div className="mt-1 text-xs text-slate-500">successful transactions</div></div><div className="rounded-xl bg-violet-300/10 p-4"><div className="text-xs text-slate-400">Operational score</div><div className="mt-2 text-2xl font-bold text-violet-300">{d.operations}/100</div><div className="mt-1 text-xs text-slate-500">execution efficiency</div></div></div><div className="mt-6 rounded-xl bg-black/20 p-5"><div className="text-xs uppercase tracking-widest text-cyan-300">Governor summary</div><p className="mt-2 leading-7 text-slate-300">{mode==="finance"?`Finance is producing ${money(net)} net income in the selected ${period} period. Sales are ${money(d.sales)}, while expenses are ${money(d.expenses)}. The main governance priority is profitable growth: protect cash flow, reduce leakage and direct investment toward the highest-return company operations.`:`Operations are running at ${d.operations}% efficiency with ${successRate}% transaction success. The governance priority is execution: reduce avoidable failures, automate repetitive workflows and keep sales growth aligned with sustainable operating costs.`}</p></div></section><section className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-2"><Lightbulb className="text-amber-300" size={19}/><h2 className="font-semibold">Growth suggestions</h2></div><div className="mt-5 space-y-3">{suggestions.map((s,i)=><div key={i} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="text-xs text-cyan-300">Recommendation {i+1}</div><p className="mt-2 text-sm leading-6 text-slate-300">{s}</p></div>)}</div><button className="mt-5 w-full rounded-xl bg-cyan-300 text-slate-950 p-3 font-semibold flex items-center justify-center gap-2"><BrainCircuit size={17}/> Ask Xedruo AI for a growth plan</button></section></div>
 <div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="font-semibold">Executive KPI trend</h2><div className="mt-5 grid md:grid-cols-4 gap-3">{[["Sales growth","+12.8%","vs previous period"],["Net margin",`${Math.round(net/d.income*100)}%","income retained"],["Failed transactions",d.failed,"needs review"],["Operations",`${d.operations}%","execution score"]].map(([l,v,s])=><div key={l} className="rounded-xl bg-black/20 p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-2 text-xl font-bold">{v}</div><div className="text-xs text-slate-600 mt-1">{s}</div></div>)}</div></div>
 </div></div>;
}
