export const COUNTRY_METADATA = [
  { code: "AW", name: "Aruba", currency: "AWG", timeZone: "America/Aruba" },
  { code: "AF", name: "Afghanistan", currency: "AFN", timeZone: "Asia/Kabul" },
  { code: "AO", name: "Angola", currency: "AOA", timeZone: "Africa/Luanda" },
  { code: "AI", name: "Anguilla", currency: "XCD", timeZone: "America/Anguilla" },
  { code: "AX", name: "Åland Islands", currency: "EUR", timeZone: "Europe/Mariehamn" },
  { code: "AL", name: "Albania", currency: "ALL", timeZone: "Europe/Tirane" },
  { code: "AD", name: "Andorra", currency: "EUR", timeZone: "Europe/Andorra" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", timeZone: "Asia/Dubai" },
  { code: "AR", name: "Argentina", currency: "ARS", timeZone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", currency: "AMD", timeZone: "Asia/Yerevan" },
  { code: "AS", name: "American Samoa", currency: "USD", timeZone: "Pacific/Pago_Pago" },
  { code: "AQ", name: "Antarctica", currency: "USD", timeZone: "Antarctica/McMurdo" },
  { code: "TF", name: "French Southern Territories", currency: "EUR", timeZone: "Indian/Kerguelen" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", timeZone: "America/Antigua" },
  { code: "AU", name: "Australia", currency: "AUD", timeZone: "Australia/Lord_Howe" },
  { code: "AT", name: "Austria", currency: "EUR", timeZone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", timeZone: "Asia/Baku" },
  { code: "BI", name: "Burundi", currency: "BIF", timeZone: "Africa/Bujumbura" },
  { code: "BE", name: "Belgium", currency: "EUR", timeZone: "Europe/Brussels" },
  { code: "BJ", name: "Benin", currency: "XOF", timeZone: "Africa/Porto-Novo" },
  { code: "BQ", name: "Caribbean Netherlands", currency: "USD", timeZone: "America/Kralendijk" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", timeZone: "Africa/Ouagadougou" },
  { code: "BD", name: "Bangladesh", currency: "BDT", timeZone: "Asia/Dhaka" },
  { code: "BG", name: "Bulgaria", currency: "BGN", timeZone: "Europe/Sofia" },
  { code: "BH", name: "Bahrain", currency: "BHD", timeZone: "Asia/Bahrain" },
  { code: "BS", name: "Bahamas", currency: "BSD", timeZone: "America/Nassau" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", timeZone: "Europe/Sarajevo" },
  { code: "BL", name: "Saint Barthélemy", currency: "EUR", timeZone: "America/St_Barthelemy" },
  { code: "BY", name: "Belarus", currency: "BYN", timeZone: "Europe/Minsk" },
  { code: "BZ", name: "Belize", currency: "BZD", timeZone: "America/Belize" },
  { code: "BM", name: "Bermuda", currency: "BMD", timeZone: "Atlantic/Bermuda" },
  { code: "BO", name: "Bolivia", currency: "BOB", timeZone: "America/La_Paz" },
  { code: "BR", name: "Brazil", currency: "BRL", timeZone: "America/Sao_Paulo" },
  { code: "BB", name: "Barbados", currency: "BBD", timeZone: "America/Barbados" },
  { code: "BN", name: "Brunei", currency: "BND", timeZone: "Asia/Brunei" },
  { code: "BT", name: "Bhutan", currency: "BTN", timeZone: "Asia/Thimphu" },
  { code: "BV", name: "Bouvet Island", currency: "NOK", timeZone: "UTC" },
  { code: "BW", name: "Botswana", currency: "BWP", timeZone: "Africa/Gaborone" },
  { code: "CF", name: "Central African Republic", currency: "XAF", timeZone: "Africa/Bangui" },
  { code: "CA", name: "Canada", currency: "CAD", timeZone: "America/St_Johns" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency: "AUD", timeZone: "Indian/Cocos" },
  { code: "CH", name: "Switzerland", currency: "CHF", timeZone: "Europe/Zurich" },
  { code: "CL", name: "Chile", currency: "CLP", timeZone: "America/Santiago" },
  { code: "CN", name: "China", currency: "CNY", timeZone: "Asia/Shanghai" },
  { code: "CI", name: "Côte d’Ivoire", currency: "XOF", timeZone: "Africa/Abidjan" },
  { code: "CM", name: "Cameroon", currency: "XAF", timeZone: "Africa/Douala" },
  { code: "CD", name: "Democratic Republic of the Congo", currency: "CDF", timeZone: "Africa/Kinshasa" },
  { code: "CG", name: "Republic of the Congo", currency: "XAF", timeZone: "Africa/Brazzaville" },
  { code: "CK", name: "Cook Islands", currency: "NZD", timeZone: "Pacific/Rarotonga" },
  { code: "CO", name: "Colombia", currency: "COP", timeZone: "America/Bogota" },
  { code: "KM", name: "Comoros", currency: "KMF", timeZone: "Indian/Comoro" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", timeZone: "Atlantic/Cape_Verde" },
  { code: "CR", name: "Costa Rica", currency: "CRC", timeZone: "America/Costa_Rica" },
  { code: "CU", name: "Cuba", currency: "CUP", timeZone: "America/Havana" },
  { code: "CW", name: "Curaçao", currency: "ANG", timeZone: "America/Curacao" },
  { code: "CX", name: "Christmas Island", currency: "AUD", timeZone: "Indian/Christmas" },
  { code: "CY", name: "Cyprus", currency: "EUR", timeZone: "Asia/Nicosia" },
  { code: "CZ", name: "Czechia", currency: "CZK", timeZone: "Europe/Prague" },
  { code: "DE", name: "Germany", currency: "EUR", timeZone: "Europe/Berlin" },
  { code: "DJ", name: "Djibouti", currency: "DJF", timeZone: "Africa/Djibouti" },
  { code: "DK", name: "Denmark", currency: "DKK", timeZone: "Europe/Copenhagen" },
  { code: "DM", name: "Dominica", currency: "XCD", timeZone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", timeZone: "America/Santo_Domingo" },
  { code: "DZ", name: "Algeria", currency: "DZD", timeZone: "Africa/Algiers" },
  { code: "EC", name: "Ecuador", currency: "USD", timeZone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", currency: "EGP", timeZone: "Africa/Cairo" },
  { code: "ER", name: "Eritrea", currency: "ERN", timeZone: "Africa/Asmara" },
  { code: "EH", name: "Western Sahara", currency: "MAD", timeZone: "Africa/El_Aaiun" },
  { code: "ES", name: "Spain", currency: "EUR", timeZone: "Europe/Madrid" },
  { code: "EE", name: "Estonia", currency: "EUR", timeZone: "Europe/Tallinn" },
  { code: "ET", name: "Ethiopia", currency: "ETB", timeZone: "Africa/Addis_Ababa" },
  { code: "FI", name: "Finland", currency: "EUR", timeZone: "Europe/Helsinki" },
  { code: "FJ", name: "Fiji", currency: "FJD", timeZone: "Pacific/Fiji" },
  { code: "FK", name: "Falkland Islands", currency: "FKP", timeZone: "Atlantic/Stanley" },
  { code: "FR", name: "France", currency: "EUR", timeZone: "Europe/Paris" },
  { code: "FO", name: "Faroe Islands", currency: "DKK", timeZone: "Atlantic/Faroe" },
  { code: "FM", name: "Micronesia", currency: "USD", timeZone: "Pacific/Pohnpei" },
  { code: "GA", name: "Gabon", currency: "XAF", timeZone: "Africa/Libreville" },
  { code: "GB", name: "United Kingdom", currency: "GBP", timeZone: "Europe/London" },
  { code: "GD", name: "Grenada", currency: "XCD", timeZone: "America/Grenada" },
  { code: "GE", name: "Georgia", currency: "GEL", timeZone: "Asia/Tbilisi" },
  { code: "GF", name: "French Guiana", currency: "EUR", timeZone: "America/Cayenne" },
  { code: "GG", name: "Guernsey", currency: "GBP", timeZone: "Europe/Guernsey" },
  { code: "GH", name: "Ghana", currency: "GHS", timeZone: "Africa/Accra" },
  { code: "GI", name: "Gibraltar", currency: "GIP", timeZone: "Europe/Gibraltar" },
  { code: "GL", name: "Greenland", currency: "DKK", timeZone: "America/Godthab" },
  { code: "GM", name: "Gambia", currency: "GMD", timeZone: "Africa/Banjul" },
  { code: "GN", name: "Guinea", currency: "GNF", timeZone: "Africa/Conakry" },
  { code: "GP", name: "Guadeloupe", currency: "EUR", timeZone: "America/Guadeloupe" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", timeZone: "Africa/Malabo" },
  { code: "GR", name: "Greece", currency: "EUR", timeZone: "Europe/Athens" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", currency: "GBP", timeZone: "Atlantic/South_Georgia" },
  { code: "GT", name: "Guatemala", currency: "GTQ", timeZone: "America/Guatemala" },
  { code: "GU", name: "Guam", currency: "USD", timeZone: "Pacific/Guam" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", timeZone: "Africa/Bissau" },
  { code: "GY", name: "Guyana", currency: "GYD", timeZone: "America/Guyana" },
  { code: "HK", name: "Hong Kong", currency: "HKD", timeZone: "Asia/Hong_Kong" },
  { code: "HM", name: "Heard Island and McDonald Islands", currency: "AUD", timeZone: "UTC" },
  { code: "HN", name: "Honduras", currency: "HNL", timeZone: "America/Tegucigalpa" },
  { code: "HR", name: "Croatia", currency: "EUR", timeZone: "Europe/Zagreb" },
  { code: "HT", name: "Haiti", currency: "HTG", timeZone: "America/Port-au-Prince" },
  { code: "HU", name: "Hungary", currency: "HUF", timeZone: "Europe/Budapest" },
  { code: "ID", name: "Indonesia", currency: "IDR", timeZone: "Asia/Jakarta" },
  { code: "IE", name: "Ireland", currency: "EUR", timeZone: "Europe/Dublin" },
  { code: "IL", name: "Israel", currency: "ILS", timeZone: "Asia/Jerusalem" },
  { code: "IM", name: "Isle of Man", currency: "GBP", timeZone: "Europe/Isle_of_Man" },
  { code: "IN", name: "India", currency: "INR", timeZone: "Asia/Kolkata" },
  { code: "IO", name: "British Indian Ocean Territory", currency: "USD", timeZone: "Indian/Chagos" },
  { code: "IQ", name: "Iraq", currency: "IQD", timeZone: "Asia/Baghdad" },
  { code: "IR", name: "Iran", currency: "IRR", timeZone: "Asia/Tehran" },
  { code: "IS", name: "Iceland", currency: "ISK", timeZone: "Atlantic/Reykjavik" },
  { code: "IT", name: "Italy", currency: "EUR", timeZone: "Europe/Rome" },
  { code: "JE", name: "Jersey", currency: "GBP", timeZone: "Europe/Jersey" },
  { code: "JM", name: "Jamaica", currency: "JMD", timeZone: "America/Jamaica" },
  { code: "JO", name: "Jordan", currency: "JOD", timeZone: "Asia/Amman" },
  { code: "JP", name: "Japan", currency: "JPY", timeZone: "Asia/Tokyo" },
  { code: "KE", name: "Kenya", currency: "KES", timeZone: "Africa/Nairobi" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", timeZone: "Asia/Bishkek" },
  { code: "KH", name: "Cambodia", currency: "KHR", timeZone: "Asia/Phnom_Penh" },
  { code: "KI", name: "Kiribati", currency: "AUD", timeZone: "Pacific/Tarawa" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", timeZone: "America/St_Kitts" },
  { code: "KR", name: "South Korea", currency: "KRW", timeZone: "Asia/Seoul" },
  { code: "KW", name: "Kuwait", currency: "KWD", timeZone: "Asia/Kuwait" },
  { code: "KY", name: "Cayman Islands", currency: "KYD", timeZone: "America/Cayman" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", timeZone: "Asia/Almaty" },
  { code: "LA", name: "Laos", currency: "LAK", timeZone: "Asia/Vientiane" },
  { code: "LB", name: "Lebanon", currency: "LBP", timeZone: "Asia/Beirut" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", timeZone: "America/St_Lucia" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", timeZone: "Europe/Vaduz" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", timeZone: "Asia/Colombo" },
  { code: "LR", name: "Liberia", currency: "LRD", timeZone: "Africa/Monrovia" },
  { code: "LS", name: "Lesotho", currency: "LSL", timeZone: "Africa/Maseru" },
  { code: "LT", name: "Lithuania", currency: "EUR", timeZone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", currency: "EUR", timeZone: "Europe/Luxembourg" },
  { code: "LV", name: "Latvia", currency: "EUR", timeZone: "Europe/Riga" },
  { code: "LY", name: "Libya", currency: "LYD", timeZone: "Africa/Tripoli" },
  { code: "MA", name: "Morocco", currency: "MAD", timeZone: "Africa/Casablanca" },
  { code: "MC", name: "Monaco", currency: "EUR", timeZone: "Europe/Monaco" },
  { code: "MD", name: "Moldova", currency: "MDL", timeZone: "Europe/Chisinau" },
  { code: "ME", name: "Montenegro", currency: "EUR", timeZone: "Europe/Podgorica" },
  { code: "MF", name: "Saint Martin", currency: "EUR", timeZone: "America/Marigot" },
  { code: "MG", name: "Madagascar", currency: "MGA", timeZone: "Indian/Antananarivo" },
  { code: "MH", name: "Marshall Islands", currency: "USD", timeZone: "Pacific/Majuro" },
  { code: "MK", name: "North Macedonia", currency: "MKD", timeZone: "Europe/Skopje" },
  { code: "ML", name: "Mali", currency: "XOF", timeZone: "Africa/Bamako" },
  { code: "MM", name: "Myanmar", currency: "MMK", timeZone: "Asia/Rangoon" },
  { code: "MN", name: "Mongolia", currency: "MNT", timeZone: "Asia/Ulaanbaatar" },
  { code: "MO", name: "Macao", currency: "MOP", timeZone: "Asia/Macau" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", timeZone: "Pacific/Saipan" },
  { code: "MQ", name: "Martinique", currency: "EUR", timeZone: "America/Martinique" },
  { code: "MR", name: "Mauritania", currency: "MRU", timeZone: "Africa/Nouakchott" },
  { code: "MS", name: "Montserrat", currency: "XCD", timeZone: "America/Montserrat" },
  { code: "MT", name: "Malta", currency: "EUR", timeZone: "Europe/Malta" },
  { code: "MU", name: "Mauritius", currency: "MUR", timeZone: "Indian/Mauritius" },
  { code: "MV", name: "Maldives", currency: "MVR", timeZone: "Indian/Maldives" },
  { code: "MW", name: "Malawi", currency: "MWK", timeZone: "Africa/Blantyre" },
  { code: "MX", name: "Mexico", currency: "MXN", timeZone: "America/Mexico_City" },
  { code: "MY", name: "Malaysia", currency: "MYR", timeZone: "Asia/Kuala_Lumpur" },
  { code: "MZ", name: "Mozambique", currency: "MZN", timeZone: "Africa/Maputo" },
  { code: "NA", name: "Namibia", currency: "NAD", timeZone: "Africa/Windhoek" },
  { code: "NC", name: "New Caledonia", currency: "XPF", timeZone: "Pacific/Noumea" },
  { code: "NE", name: "Niger", currency: "XOF", timeZone: "Africa/Niamey" },
  { code: "NF", name: "Norfolk Island", currency: "AUD", timeZone: "Pacific/Norfolk" },
  { code: "NG", name: "Nigeria", currency: "NGN", timeZone: "Africa/Lagos" },
  { code: "NI", name: "Nicaragua", currency: "NIO", timeZone: "America/Managua" },
  { code: "NL", name: "Netherlands", currency: "EUR", timeZone: "Europe/Amsterdam" },
  { code: "NO", name: "Norway", currency: "NOK", timeZone: "Europe/Oslo" },
  { code: "NP", name: "Nepal", currency: "NPR", timeZone: "Asia/Kathmandu" },
  { code: "NR", name: "Nauru", currency: "AUD", timeZone: "Pacific/Nauru" },
  { code: "NU", name: "Niue", currency: "NZD", timeZone: "Pacific/Niue" },
  { code: "NZ", name: "New Zealand", currency: "NZD", timeZone: "Pacific/Auckland" },
  { code: "OM", name: "Oman", currency: "OMR", timeZone: "Asia/Muscat" },
  { code: "PA", name: "Panama", currency: "PAB", timeZone: "America/Panama" },
  { code: "PE", name: "Peru", currency: "PEN", timeZone: "America/Lima" },
  { code: "PF", name: "French Polynesia", currency: "XPF", timeZone: "Pacific/Tahiti" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", timeZone: "Pacific/Port_Moresby" },
  { code: "PH", name: "Philippines", currency: "PHP", timeZone: "Asia/Manila" },
  { code: "PK", name: "Pakistan", currency: "PKR", timeZone: "Asia/Karachi" },
  { code: "PL", name: "Poland", currency: "PLN", timeZone: "Europe/Warsaw" },
  { code: "PM", name: "Saint Pierre and Miquelon", currency: "EUR", timeZone: "America/Miquelon" },
  { code: "PN", name: "Pitcairn", currency: "NZD", timeZone: "Pacific/Pitcairn" },
  { code: "PR", name: "Puerto Rico", currency: "USD", timeZone: "America/Puerto_Rico" },
  { code: "PS", name: "Palestine", currency: "ILS", timeZone: "Asia/Gaza" },
  { code: "PT", name: "Portugal", currency: "EUR", timeZone: "Europe/Lisbon" },
  { code: "PW", name: "Palau", currency: "USD", timeZone: "Pacific/Palau" },
  { code: "PY", name: "Paraguay", currency: "PYG", timeZone: "America/Asuncion" },
  { code: "QA", name: "Qatar", currency: "QAR", timeZone: "Asia/Qatar" },
  { code: "RE", name: "Réunion", currency: "EUR", timeZone: "Indian/Reunion" },
  { code: "RO", name: "Romania", currency: "RON", timeZone: "Europe/Bucharest" },
  { code: "RS", name: "Serbia", currency: "RSD", timeZone: "Europe/Belgrade" },
  { code: "RU", name: "Russia", currency: "RUB", timeZone: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", currency: "RWF", timeZone: "Africa/Kigali" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", timeZone: "Asia/Riyadh" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", timeZone: "Pacific/Guadalcanal" },
  { code: "SC", name: "Seychelles", currency: "SCR", timeZone: "Indian/Mahe" },
  { code: "SD", name: "Sudan", currency: "SDG", timeZone: "Africa/Khartoum" },
  { code: "SE", name: "Sweden", currency: "SEK", timeZone: "Europe/Stockholm" },
  { code: "SG", name: "Singapore", currency: "SGD", timeZone: "Asia/Singapore" },
  { code: "SH", name: "Saint Helena", currency: "SHP", timeZone: "Atlantic/St_Helena" },
  { code: "SI", name: "Slovenia", currency: "EUR", timeZone: "Europe/Ljubljana" },
  { code: "SJ", name: "Svalbard and Jan Mayen", currency: "NOK", timeZone: "Arctic/Longyearbyen" },
  { code: "SK", name: "Slovakia", currency: "EUR", timeZone: "Europe/Bratislava" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", timeZone: "Africa/Freetown" },
  { code: "SM", name: "San Marino", currency: "EUR", timeZone: "Europe/San_Marino" },
  { code: "SN", name: "Senegal", currency: "XOF", timeZone: "Africa/Dakar" },
  { code: "SO", name: "Somalia", currency: "SOS", timeZone: "Africa/Mogadishu" },
  { code: "SR", name: "Suriname", currency: "SRD", timeZone: "America/Paramaribo" },
  { code: "SS", name: "South Sudan", currency: "SSP", timeZone: "Africa/Juba" },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", timeZone: "Africa/Sao_Tome" },
  { code: "SV", name: "El Salvador", currency: "USD", timeZone: "America/El_Salvador" },
  { code: "SX", name: "Sint Maarten", currency: "ANG", timeZone: "America/Lower_Princes" },
  { code: "SY", name: "Syria", currency: "SYP", timeZone: "Asia/Damascus" },
  { code: "SZ", name: "Eswatini", currency: "SZL", timeZone: "Africa/Mbabane" },
  { code: "TC", name: "Turks and Caicos Islands", currency: "USD", timeZone: "America/Grand_Turk" },
  { code: "TD", name: "Chad", currency: "XAF", timeZone: "Africa/Ndjamena" },
  { code: "TF", name: "French Southern Territories", currency: "EUR", timeZone: "Indian/Kerguelen" },
  { code: "TG", name: "Togo", currency: "XOF", timeZone: "Africa/Lome" },
  { code: "TH", name: "Thailand", currency: "THB", timeZone: "Asia/Bangkok" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", timeZone: "Asia/Dushanbe" },
  { code: "TK", name: "Tokelau", currency: "NZD", timeZone: "Pacific/Fakaofo" },
  { code: "TL", name: "Timor-Leste", currency: "USD", timeZone: "Asia/Dili" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", timeZone: "Asia/Ashgabat" },
  { code: "TN", name: "Tunisia", currency: "TND", timeZone: "Africa/Tunis" },
  { code: "TO", name: "Tonga", currency: "TOP", timeZone: "Pacific/Tongatapu" },
  { code: "TR", name: "Türkiye", currency: "TRY", timeZone: "Europe/Istanbul" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", timeZone: "America/Port_of_Spain" },
  { code: "TV", name: "Tuvalu", currency: "AUD", timeZone: "Pacific/Funafuti" },
  { code: "TW", name: "Taiwan", currency: "TWD", timeZone: "Asia/Taipei" },
  { code: "TZ", name: "Tanzania", currency: "TZS", timeZone: "Africa/Dar_es_Salaam" },
  { code: "UA", name: "Ukraine", currency: "UAH", timeZone: "Europe/Kyiv" },
  { code: "UG", name: "Uganda", currency: "UGX", timeZone: "Africa/Kampala" },
  { code: "UM", name: "United States Minor Outlying Islands", currency: "USD", timeZone: "Pacific/Wake" },
  { code: "US", name: "United States", currency: "USD", timeZone: "America/New_York" },
  { code: "UY", name: "Uruguay", currency: "UYU", timeZone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", timeZone: "Asia/Tashkent" },
  { code: "VA", name: "Vatican City", currency: "EUR", timeZone: "Europe/Vatican" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", timeZone: "America/St_Vincent" },
  { code: "VE", name: "Venezuela", currency: "VES", timeZone: "America/Caracas" },
  { code: "VG", name: "British Virgin Islands", currency: "USD", timeZone: "America/Tortola" },
  { code: "VI", name: "U.S. Virgin Islands", currency: "USD", timeZone: "America/St_Thomas" },
  { code: "VN", name: "Vietnam", currency: "VND", timeZone: "Asia/Ho_Chi_Minh" },
  { code: "VU", name: "Vanuatu", currency: "VUV", timeZone: "Pacific/Efate" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", timeZone: "Pacific/Wallis" },
  { code: "WS", name: "Samoa", currency: "WST", timeZone: "Pacific/Apia" },
  { code: "YE", name: "Yemen", currency: "YER", timeZone: "Asia/Aden" },
  { code: "YT", name: "Mayotte", currency: "EUR", timeZone: "Indian/Mayotte" },
  { code: "ZA", name: "South Africa", currency: "ZAR", timeZone: "Africa/Johannesburg" },
  { code: "ZM", name: "Zambia", currency: "ZMW", timeZone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWG", timeZone: "Africa/Harare" },
];

export const COUNTRY_BY_CODE = Object.fromEntries(COUNTRY_METADATA.map((country) => [country.code, country]));
